import type { Metadata } from 'next';
import './globals.css';
import { Container } from './_components/Container';

export const metadata: Metadata = {
  title: 'microCMS+Next.js Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className="flex flex-col min-h-screen">
        <Container>{children}</Container>
        <footer className="mt-auto mb-2 text-center">
          <p>© runfunrun</p>
        </footer>
      </body>
    </html>
  );
}
